package main

import (
	"math"
	"net/http/httptest"
	"strings"
	"testing"

	dto "github.com/prometheus/client_model/go"
	"github.com/prometheus/common/expfmt"
	promModel "github.com/prometheus/common/model"
)

// The exposition is hand-written with Fprintf rather than generated by a client
// library, so nothing but a parse proves it is still valid - and a malformed
// histogram would be indistinguishable from a bug in the TUI reading it.
func TestExpositionParsesAndHistogramsAreCumulative(t *testing.T) {
	state := NewMetricsState()
	state.Update()

	rec := httptest.NewRecorder()
	state.Write(rec)

	parser := expfmt.NewTextParser(promModel.UTF8Validation)
	families, err := parser.TextToMetricFamilies(strings.NewReader(rec.Body.String()))
	if err != nil {
		t.Fatalf("exposition does not parse: %v", err)
	}

	for _, name := range []string{"http_request_duration_seconds", "http_response_size_bytes"} {
		family := families[name]
		if family == nil {
			t.Fatalf("%s missing from the exposition", name)
		}
		for _, metric := range family.GetMetric() {
			prev := uint64(0)
			for _, bucket := range metric.GetHistogram().GetBucket() {
				if bucket.GetCumulativeCount() < prev {
					t.Errorf("%s le=%v count %d is below the bucket under it (%d)",
						name, bucket.GetUpperBound(), bucket.GetCumulativeCount(), prev)
				}
				prev = bucket.GetCumulativeCount()
			}
			if got := metric.GetHistogram().GetSampleCount(); got < prev {
				t.Errorf("%s _count %d is below its largest bucket %d", name, got, prev)
			}
		}
	}

	// The two families must not share a bucket layout, or the view's "bounds are
	// not a common axis" case never arises against this server.
	latency := boundsOf(t, families, "http_request_duration_seconds")
	sizes := boundsOf(t, families, "http_response_size_bytes")
	for _, a := range latency {
		for _, b := range sizes {
			if a == b && !math.IsInf(a, +1) {
				t.Errorf("the two histograms share the finite bound %v", a)
			}
		}
	}
}

// Each handler must land in a visibly different part of the bucket range, or the
// labelled histogram shows three copies of the same shape.
func TestHandlerProfilesHaveDistinctShapes(t *testing.T) {
	state := NewMetricsState()

	rec := httptest.NewRecorder()
	state.Write(rec)
	parser := expfmt.NewTextParser(promModel.UTF8Validation)
	families, err := parser.TextToMetricFamilies(strings.NewReader(rec.Body.String()))
	if err != nil {
		t.Fatalf("exposition does not parse: %v", err)
	}

	// Share of observations at or below 0.2s, which is where the profiles differ.
	share := map[string]float64{}
	for _, metric := range families["http_request_duration_seconds"].GetMetric() {
		handler := ""
		for _, label := range metric.GetLabel() {
			if label.GetName() == "handler" {
				handler = label.GetValue()
			}
		}
		for _, bucket := range metric.GetHistogram().GetBucket() {
			if bucket.GetUpperBound() == 0.2 {
				share[handler] = float64(bucket.GetCumulativeCount()) / float64(metric.GetHistogram().GetSampleCount())
			}
		}
	}

	if len(share) != 3 {
		t.Fatalf("got %d handlers, want 3: %v", len(share), share)
	}
	if share["/fast"] < 0.95 {
		t.Errorf("/fast puts only %.2f of its observations under 0.2s, want nearly all", share["/fast"])
	}
	if share["/slow"] > 0.05 {
		t.Errorf("/slow puts %.2f of its observations under 0.2s, want almost none", share["/slow"])
	}
	if share["/bimodal"] < 0.5 || share["/bimodal"] > 0.9 {
		t.Errorf("/bimodal puts %.2f under 0.2s, want a split between two bands", share["/bimodal"])
	}
}

func boundsOf(t *testing.T, families map[string]*dto.MetricFamily, name string) []float64 {
	t.Helper()
	var bounds []float64
	for _, bucket := range families[name].GetMetric()[0].GetHistogram().GetBucket() {
		bounds = append(bounds, bucket.GetUpperBound())
	}
	return bounds
}
